name: Environment Variables in GitHub Actions

on: [push]

env:
    PUBLICENV: THIS IS A PUBLIC VARIABLE - Available for all jobs

jobs:
    sample-job-1:
        runs-on: ubuntu-latest
        env:
            JOBENV: THIS IS A JOB SPECIFIC VARIABLE - Available for this job only
        steps:
            - name: Demo a step level env variable
              env:
                  STEPENV: THIS IS A STEP SPECIFIC VARIABLE - Available for this step only
              run: echo "${STEPENV}"

            - name: echo env variables
              run: |
                  echo "${PUBLICENV}"
                  echo "${JOBENV}"
                  echo "${STEPENV}"
                  echo "Home: ${HOME}"
                  echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"
                  echo "GITHUB_ACTIONS: ${GITHUB_ACTIONS}"
                  echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
                  echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
                  echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
                  echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
                  echo "GITHUB_SHA: ${GITHUB_SHA}"
                  echo "GITHUB_REF: ${GITHUB_REF}"
                  echo "PublicENV1: ${PublicENV1}"
                  echo "JOB_ENV: ${JOB_ENV}"
                  echo "step_ENV: ${step_ENV}"

    sample-job-2:
        runs-on: ubuntu-latest
        steps:
            - name: echo env variables
              run: |
                  echo "${PUBLICENV}"
                  echo "${JOBENV}"
                  echo "${STEPENV}"
                  
